spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cartdb
    username: cart
    password: password

  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://keycloak:8080/realms/auth
        client:
          registration:
            keycloak:
              authorization-grant-type: client_credentials
              client-id: cart-client
              client-secret: etlxnIPSbCpjiPJfz6lyVTXphNF2xamy
              scope: openid
              provider: keycloak
          provider:
            keycloak:
              token-uri: http://keycloak:8080/realms/auth/protocol/openid-connect/token

  # cloud:
  #   openfeign:
  #     oauth2:
  #       enabled: true
  #       clientRegistrationId: keycloak
            
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: create-drop
    
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true

server:
  port: 8082
