spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/cartdb
    username: cart
    password: password

  security:
      oauth2:
        resourceserver:
          jwt:
            issuer-uri: http://keycloak:8080/realms/auth
            
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
      ddl-auto: create-drop
    
    properties:
      hibernate:
        format_sql: true
        globally_quoted_identifiers: true
        
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: cart-service
      auto-offset-reset: earliest
      properties:
        spring:
          json:
            type.mapping: Event:com.bookstore.cartservice.dto.Event
            trusted.packages: "*"

server:
  port: 8082
