spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/catalogdb
    username: catalog
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

    hibernate:
      ddl-auto: create-drop
    
    properties:
      hibernate:
        format_sql: true
        # ddl-auto: create

server:
  port: 8081
