spring:
  datasource:
    url: jdbc:postgresql://catalog:5432/catalogdb
    username: catalog
    password: password

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop

server:
  port: 8081
