spring:
    cloud:
        config:
            enabled: true
        
        gateway:
          routes:
            - id: catalog
              uri: http://catalog:8081/
              predicates:
                - Path=/catalog/**
    
    security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://keycloak:8080/realms/auth
              jwk-set-uri: http://keycloak:8080/realms/auth/protocol/openid-connect/certs
server:
  port: 8000

# ---
# spring:
#     # cloud:
#     #     gateway:
#     #       routes:
#     #         - id: catalog
#     #           uri: http://catalog:8081/
#     #           predicates:
#     #             - Path=/catalog/**
    
#     security:
#         oauth2:
#           resourceserver:
#             jwt:
#               issuer-uri: http://keycloak:8080/realms/auth
