spring:
    cloud:
        config:
            enabled: true
        
        gateway:
            discovery:
                locator:
                    enabled: true
                    lower-case-service-id: true
server:
  port: 8000
