spring:
    cloud:
        config:
            enabled: true
        
        gateway:
          routes:
            - id: catalog
              uri: http://localhost:8081/
              predicates:
                - Path=/catalog/**
    
    security:
        oauth2:
          resourceserver:
            jwt:
              issuer-uri: http://localhost:9000/realms/auth
server:
  port: 8000

eureka:
  client:
    serviceUrl:
      defaultZone: http://root:s3cr3t@localhost:8761/eureka
  instance:
    hostname: localhost