spring:
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/orderdb
    username: orders
    password: password

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/auth

server:
  port: 8083
